/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PrayerTimeLazyImport = createFileRoute('/prayerTime')()
const JadwalLazyImport = createFileRoute('/jadwal')()
const CatatanLazyImport = createFileRoute('/catatan')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PrayerTimeLazyRoute = PrayerTimeLazyImport.update({
  path: '/prayerTime',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/prayerTime.lazy').then((d) => d.Route))

const JadwalLazyRoute = JadwalLazyImport.update({
  path: '/jadwal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/jadwal.lazy').then((d) => d.Route))

const CatatanLazyRoute = CatatanLazyImport.update({
  path: '/catatan',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/catatan.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/catatan': {
      preLoaderRoute: typeof CatatanLazyImport
      parentRoute: typeof rootRoute
    }
    '/jadwal': {
      preLoaderRoute: typeof JadwalLazyImport
      parentRoute: typeof rootRoute
    }
    '/prayerTime': {
      preLoaderRoute: typeof PrayerTimeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  CatatanLazyRoute,
  JadwalLazyRoute,
  PrayerTimeLazyRoute,
])

/* prettier-ignore-end */
